spring:
  cloud:
    nacos:
      config:
        server-addr: 119.91.202.204:8848
        namespace: a97fa0e8-6034-4cfc-bf49-e44fe6ad149b
      discovery:
        ip: 119.91.202.204
        server-addr: 119.91.202.204:8848
    gateway:
      routes:
        - id: test_router
          uri: https://www.baidu.com
          predicates:
            - Query=url, baidu

        - id: qq_route
          uri: http://127.0.0.1:8080/coupon/coupon/list
          predicates:
            - Query=url, qq
  #  config:
#    import:
#      - optional:nacos:gulimall-gateway.yml?refreshEnabled=true # 开启动态刷新
  application:
    name: gulimall-gateway
server:
  port: 88
