spring:
  cloud:
    nacos:
      config:
        server-addr: portgas.cn:8848
        namespace: a97fa0e8-6034-4cfc-bf49-e44fe6ad149b
      discovery:
        ip: portgas.cn
        server-addr: portgas.cn:8848
    gateway:
      # 所有外部接口都带上api前缀
      routes:
        - id: product_route
          # 目标URL，lb代表从注册中心获取服务，lb是Load Balance的缩写
          # 这里后面改lb
          uri: http://192.168.10.103:10000/gulimall-product
          # uri: http://192.168.9.81:10000/gulimall-product
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/?(?<segment>.*), /$\{segment}

        - id: member_route
          # 目标URL，lb代表从注册中心获取服务，lb是Load Balance的缩写
          # 这里后面改lb
          uri: http://192.168.10.103:20000/gulimall-member
          # uri: http://192.168.9.81:10000/gulimall-product
          predicates:
            - Path=/api/member/**
          filters:
            - RewritePath=/api/?(?<segment>.*), /$\{segment}

        - id: third_party_route
          # 目标URL，lb代表从注册中心获取服务，lb是Load Balance的缩写
          # 这里后面改lb
          uri: http://192.168.10.103:30000/gulimall-third-party
          predicates:
            - Path=/api/thirdparty/**
          filters:
            - RewritePath=/api/thirdparty/(?<segment>.*), /$\{segment}

        - id: admin_route
          uri: http://192.168.10.103:10001/renren-fast
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/?(?<segment>.*), /renren-fast/$\{segment}

  application:
    name: gulimall-gateway
server:
  port: 80
